theme: jekyll-theme-tactile
permalink: pretty
title: "Nano (なの) Docs"
description: "Documentation of Nano framework"
logo: "https://raw.githubusercontent.com/CamilleAbella/Nano/master/assets/images/logo.png"